---
- hosts: all
  user: deployer
  become: True
  tasks:
    - name: Add repository
      yum_repository:
      name: epel
      description: EPEL YUM repo
      baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/

    - name: yum-clean-metadata
      command: yum clean metadata
         args:
         warn: no
