---
- hosts: centos
  gather_facts: false
  become: true
  tasks:
- name: Installing Remi Repository
  yum:
   name: https://rpms.remirepo.net/enterprise/remi-release-7.rpm
   state: present

- name: Installing php
  yum:
  enablerepo: "remi,remi-php80" # If you intent to install a different version of PHP, you can change the repo according. Eg : "remi,remi-php74"
- name:
  - php
  - php-common
  - php-cli
  - php-gd
  - php-curl #You can add or remove PHP extensions according to your choice
  - php-mysqlnd
  - php-fpm
  - php-mysqli 
  state: latest
