---
- name: Ansible Create User
  hosts: centos
  tasks:
    - name: Add the user 'clown' with a specific uid and a primary group of 'wheel'
      ansible.builtin.user:
        name: clown
        comment: clown user
        uid: 1077
        group: wheel
        createhome: yes
        home: /home/clown
